name: deploy-to-eb

on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'aws'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create ZIP deployment package
        run: zip -r deploy_package.zip ./backend

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-region: "ap-southeast-1"

      - name: Upload package to S3 bucket
        run: aws s3 cp deploy_package.zip s3://aws-bucket-25846/

      - name: Create new ElasticBeanstalk Application Version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name my_test_app_25846 \
          --source-bundle S3Bucket="aws-bucket-25846",S3Key="deploy_package.zip" \
          --version-label "ver-${{ github.sha }}" \
          --description "commit-sha-${{ github.sha }}"

      - name: Deploy new ElasticBeanstalk Application Version
        run: aws elasticbeanstalk update-environment --environment-name Mytestapp25846-env --version-label "ver-${{ github.sha }}"